### ISSUE TITLE
Question - Rerunning terraform from different computers wants to replace a lot of thing in the flux boot strap

### ISSUE THREAD

**Issue by btsteve** [kube-champ/terraform-k8s-flux-bootstrap#7]
I am trying to run terraform from a different computer than the eks clusters were deployed from. 
When I do i get that it will destroy and create 17 things. 

This is the first time using this on a different computer. Is this an expected behavior?

Example:
```yaml
# module.flux-bootstrap.kubectl_manifest.apply["17acf2a4160b0555ad899b871dc7a3731efde14c"] will be destroyed
  # (because key ["17acf2a4160b0555ad899b871dc7a3731efde14c"] is not in for_each map)
  - resource "kubectl_manifest" "apply" {
      - api_version             = "apiextensions.k8s.io/v1" -> null
      - force_new               = false -> null
      - id                      = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/helmcharts.source.toolkit.fluxcd.io" -> null
      - kind                    = "CustomResourceDefinition" -> null
      - live_manifest_incluster = (sensitive value)
      - live_uid                = "70536f07-47d7-4c09-858a-42b4ebea4fc6" -> null
      - name                    = "helmcharts.source.toolkit.fluxcd.io" -> null
      - server_side_apply       = false -> null
      - uid                     = "70536f07-47d7-4c09-858a-42b4ebea4fc6" -> null
      - validate_schema         = true -> null
      - wait_for_rollout        = true -> null
      - yaml_body               = (sensitive value)
      - yaml_body_parsed        = <<-EOT
            apiVersion: apiextensions.k8s.io/v1
            kind: CustomResourceDefinition
            metadata:
              annotations:
                controller-gen.kubebuilder.io/version: v0.7.0
              creationTimestamp: null
              labels:
                app.kubernetes.io/instance: flux-system
                app.kubernetes.io/part-of: flux
                app.kubernetes.io/version: latest
              name: helmcharts.source.toolkit.fluxcd.io
```
